### PR TITLE
Fix cl-defstruct typo

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by stefanv** [comment]
@jtmoulia Are you still maintaining this project? If not, would it benefit from other maintainers?

**Comment by jtmoulia** [comment]
Hi @stefanv  -- I haven't been maintaining the project actively over the last year or so, but I do hope to have more time starting this week.

That being said, happy to add other people who are interested in taking an active hand.

**Comment by stefanv** [comment]
Excellent! I am happy to keep contributing via PRs of we can get those merged.

**Comment by jtmoulia** [comment]
Thanks for sticking with it -- merged

**Pull request merged**
